CREATE TABLE `agents` (
  `agent_id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `phone` VARCHAR(15) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `email_verified` TINYINT(1) NOT NULL DEFAULT 0,
  `email_verified_at` DATETIME DEFAULT NULL,
  `email_verification_token` VARCHAR(128) DEFAULT NULL,
  `email_verification_sent_at` DATETIME DEFAULT NULL,
  `email_verification_attempts` INT NOT NULL DEFAULT 0,
  `password` VARCHAR(255) NOT NULL,
  `profile_picture` VARCHAR(500) DEFAULT NULL,
  `license_number` VARCHAR(50) DEFAULT NULL,
  `experience_years` INT DEFAULT 0,
  `specializations` JSON DEFAULT NULL,
  `hourly_rate` DECIMAL(10,2) DEFAULT 0.00,
  `availability_status` ENUM('available','busy','offline') NOT NULL DEFAULT 'offline',
  `business_name` VARCHAR(150) DEFAULT NULL,
  `tax_id` VARCHAR(50) DEFAULT NULL,
  `insurance_details` TEXT DEFAULT NULL,
  `certifications` JSON DEFAULT NULL,
  `current_latitude` DECIMAL(10,8) DEFAULT NULL,
  `current_longitude` DECIMAL(11,8) DEFAULT NULL,
  `service_radius` INT DEFAULT 10,
  `base_address` TEXT DEFAULT NULL,
  `city` VARCHAR(100) DEFAULT NULL,
  `state` VARCHAR(100) DEFAULT NULL,
  `zipcode` VARCHAR(10) DEFAULT NULL,
  `verification_status` ENUM('pending','verified','rejected') NOT NULL DEFAULT 'pending',
  `rating` DECIMAL(3,2) DEFAULT 0.00,
  `total_jobs_completed` INT DEFAULT 0,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `background_check_status` ENUM('pending','cleared','failed') NOT NULL DEFAULT 'pending',
  `bio` TEXT DEFAULT NULL,
  `documents` JSON DEFAULT NULL,
  `dob` DATE DEFAULT NULL COMMENT 'Date of birth',
  `gender` ENUM('male','female','other','prefer_not_to_say') DEFAULT NULL COMMENT 'Agent gender',
  `vehicle` JSON DEFAULT NULL COMMENT 'Vehicle details (JSON)',
  `emergency_contact_name` VARCHAR(100) DEFAULT NULL,
  `emergency_contact_phone` VARCHAR(15) DEFAULT NULL,
  `phone_verified` TINYINT(1) NOT NULL DEFAULT 0,
  `phone_verified_at` DATETIME DEFAULT NULL,
  `phone_verification_code` VARCHAR(128) DEFAULT NULL,
  `phone_verification_expires_at` DATETIME DEFAULT NULL,
  `phone_verification_sent_at` DATETIME DEFAULT NULL,
  `phone_verification_attempts` INT NOT NULL DEFAULT 0,
  `phone_verification_method` ENUM('sms','voice') NOT NULL DEFAULT 'sms',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `last_active_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`agent_id`),
  UNIQUE KEY `uq_agents_phone` (`phone`),
  UNIQUE KEY `uq_agents_email` (`email`),
  UNIQUE KEY `uq_agents_license_number` (`license_number`),
  KEY `idx_agents_location` (`current_latitude`,`current_longitude`),
  KEY `idx_agents_verification_status` (`verification_status`),
  KEY `idx_agents_availability_status` (`availability_status`),
  KEY `idx_agents_city_state` (`city`,`state`),
  CHECK (`rating` >= 0.00 AND `rating` <= 5.00)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;